"""Disasters and Alerts SQLAlchemy models.

Maps to the existing 'alerts', 'disaster_events', and 'disaster_sources'
tables in the database.
"""

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, ENUM, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
# Note: Geoalchemy2 would be the ideal way to map PostGIS GEOGRAPHY types.
# However, for simplicity without adding new pip packages if not permitted,
# we use Text/String for PostGIS WKT wrappers or skip mapping them directly
# if we just manage points via custom inserts, but standard is `geoalchemy2.types.Geography`.
# Since 'base_location' in existing uses PostGIS, we will map them if possible.
# Assuming geoalchemy2 might be available:
try:
    from geoalchemy2 import Geography
except ImportError:
    # Safe fallback if geoalchemy2 isn't installed
    class Geography(Text):
        def __init__(self, geometry_type="GEOMETRY", srid=4326, **kwargs):
            super().__init__()

from app.common.base_model import BaseModel


class Alert(BaseModel):
    """Alerts generated by incoming sources."""

    __tablename__ = "alerts"

    alert_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    external_ref_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    alert_type: Mapped[str] = mapped_column(
        ENUM("flood", "earthquake", "cyclone", "drought", "heatwave", "landslide", name="disaster_type", create_type=False),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_type: Mapped[str] = mapped_column(
        ENUM("sensor", "social_media", "news", "government", "citizen", "ai", "manual", name="alert_source", create_type=False),
        nullable=False,
    )
    source_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status: Mapped[str] = mapped_column(
        ENUM("new", "verified", "analyzing", "active", "monitoring", "resolved", "false_alarm", name="alert_status", create_type=False),
        nullable=False,
        server_default="new",
    )
    severity_score: Mapped[Decimal | None] = mapped_column(Numeric(3, 1), nullable=True)
    confidence_score: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)
    
    # Geography mapped
    location: Mapped[str] = mapped_column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    location_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    district: Mapped[str | None] = mapped_column(String(100), nullable=True)
    province: Mapped[str | None] = mapped_column(String(100), nullable=True)
    
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True
    )
    verified_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True
    )
    
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    disaster_event = relationship("DisasterEvent", back_populates="source_alert", uselist=False)


class DisasterEvent(BaseModel):
    """Verified disaster events that group associated alerts/sources."""

    __tablename__ = "disaster_events"

    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    source_alert_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("alerts.alert_id", ondelete="SET NULL"), unique=True, nullable=True
    )
    external_ref_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    event_type: Mapped[str] = mapped_column(
        ENUM("flood", "earthquake", "cyclone", "drought", "heatwave", "landslide", name="disaster_type", create_type=False),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    location_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    district: Mapped[str | None] = mapped_column(String(100), nullable=True)
    province: Mapped[str | None] = mapped_column(String(100), nullable=True)
    
    location: Mapped[str] = mapped_column(Geography(geometry_type="POINT", srid=4326), nullable=False)
    affected_area: Mapped[str | None] = mapped_column(Geography(geometry_type="POLYGON", srid=4326), nullable=True)
    
    affected_population: Mapped[int | None] = mapped_column(nullable=True)
    severity_score: Mapped[Decimal | None] = mapped_column(Numeric(3, 1), nullable=True)
    risk_level: Mapped[str | None] = mapped_column(
        ENUM("low", "medium", "high", "critical", name="risk_level", create_type=False), nullable=True
    )
    source_type: Mapped[str | None] = mapped_column(
        ENUM("sensor", "social_media", "news", "government", "citizen", "ai", "manual", name="alert_source", create_type=False),
        nullable=True,
    )
    event_status: Mapped[str] = mapped_column(
        ENUM("active", "monitoring", "resolved", name="disaster_event_status", create_type=False),
        nullable=False,
        server_default="active",
    )
    
    precautions: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    estimated_damage_pkr: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True
    )
    verified_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.user_id", ondelete="SET NULL"), nullable=True
    )
    
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    analyzed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    source_alert = relationship("Alert", back_populates="disaster_event")
    sources = relationship("DisasterSource", back_populates="event", cascade="all, delete")


class DisasterSource(BaseModel):
    """Append-only provenance tracking for disasters."""

    __tablename__ = "disaster_sources"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("disaster_events.event_id", ondelete="CASCADE"), nullable=False
    )
    source_type: Mapped[str | None] = mapped_column(
        ENUM("sensor", "social_media", "news", "government", "citizen", "ai", "manual", name="alert_source", create_type=False),
        nullable=True,
    )
    source_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    source_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    raw_data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    confidence_score: Mapped[Decimal | None] = mapped_column(Numeric(5, 2), nullable=True)

    # Relationships
    event = relationship("DisasterEvent", back_populates="sources")
